### ISSUE TITLE
Index templates for Wazuh Server RBAC migration

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#288]
## Description

Related issue: https://github.com/wazuh/wazuh/issues/27795

In order to migrate the Wazuh Server RBAC (role-based access control), we need to generate the index templates to migrate the databases used for it. We need to generate index templates for the `users` and `roles` tables described [here](https://github.com/wazuh/wazuh/issues/27795#issuecomment-2634778276).

The `rules` and `policies` entities could be inserted under the `roles` entity, as follows:

```json
// roles
{
  "id": "uuid",
  "name": "role-name",
  "created_at": "timestamp",
  "rules": [],
  "policies": []
}

// users
{
  "id": "uuid",
  "username": "user-name",
  "password": "user-password",
  "allow_run_as": false,
  "created_at": "timestamp",
  "roles": ["role-1", "role-2"]
}
```

Consider using indices for the `policies` entity as well, for reusability.

## Functional requirements

- An index template is generated for each entity.
- Index templates and initial and indices are created on start

## Implementation restrictions

- The index templates are ECS compliant.
- The index templates are located under the `ecs` folder, so they are autogenerated by the GitHub Workflow.

## Plan

- [x] Generate the index templates
- [x] Add them to the setup plugin.
- [x] Index templates and initial and indices are created on start.

**Comment by GGP1** [comment]
@wazuh-devel-xdrsiem-indexer 

After reviewing how we access and use the information in the current RBAC implementation, I found that it would we way better from the server's perspective to have 4 separate indices for each entity (users, roles, rules and policies).

This is because we are accessing them separately and [listing](https://github.com/wazuh/wazuh/blob/793688ff76f23a7077d1eb197934d5e39dbe0410/framework/wazuh/rbac/decorators.py#L45-L62) all the available items at once, instead of getting users and their relationships.

For example, listing all policies with just two indices would require the server to request all roles, list all the role's policies, compare them against the others to validate that they are unique and add them to the list. We could even have multiple repeated policies and therefore making the task costlier to the server.

To fix this, we could have 4 indices `users`, `roles`, `policies`, `rules` that would have the following structure:

<details><summary>Users</summary>

```yaml
id: "id"
username: "username"
password: "password_hash"
allow_run_as: false
created_at: 0
roles: ["role_id_1", "role_id_2"]
```

</details>

<details><summary>Roles</summary>

```yaml
id: "id"
name: "admin"
created_at: 0
policies: ["policy_id_1", "policy_id_2"]
rules: ["rule_id_1", "rule_id_2"]
```

</details>

<details><summary>Policies</summary>

```yaml
id: "id"
name: "policy"
policy: "body"
created_at: 0
```

> The field `policy` contains the encoded [policy body](https://github.com/wazuh/wazuh/blob/main/framework/wazuh/rbac/default/policies.yaml), we could store the object instead of a serialized JSON inside a string.

</details>

<details><summary>Rules</summary>

```yaml
id: "id"
name: "rule"
rule: "body"
created_at: 0
```

> The field `rule` contains the encoded [rule body](https://github.com/wazuh/wazuh/blob/main/framework/wazuh/rbac/default/rules.yaml), we could store the object instead of a serialized JSON inside a string.

</details>

> [!Note]
> Usernames and names must be unique, so we could use them as IDs.

**Comment by GGP1** [comment]
@wazuh-devel-xdrsiem-indexer 

After reviewing how we access and use the information in the current RBAC implementation, I found that it would we way better from the server's perspective to have 4 separate indices for each entity (users, roles, rules and policies).

This is because we are accessing them separately and [listing](https://github.com/wazuh/wazuh/blob/793688ff76f23a7077d1eb197934d5e39dbe0410/framework/wazuh/rbac/decorators.py#L45-L62) all the available items at once, instead of getting users and their relationships.

For example, listing all policies with just two indices would require the server to request all roles, list all the role's policies, compare them against the others to validate that they are unique and add them to the list. We could even have multiple repeated policies and therefore making the task costlier to the server.

To fix this, we could have 4 indices `users`, `roles`, `policies`, `rules` that would have the following structure:

<details><summary>Users</summary>

```yaml
id: "id"
username: "username"
password: "password_hash"
allow_run_as: false
created_at: 0
roles: ["role_id_1", "role_id_2"]
```

</details>

<details><summary>Roles</summary>

```yaml
id: "id"
name: "admin"
created_at: 0
policies: ["policy_id_1", "policy_id_2"]
rules: ["rule_id_1", "rule_id_2"]
```

</details>

<details><summary>Policies</summary>

```yaml
id: "id"
name: "policy"
actions: ["agent:create"]
resources: ["*:*:*"]
effect: "allow"
created_at: 0
```

</details>

<details><summary>Rules</summary>

```yaml
id: "id"
name: "rule"
FIND|MATCH:
  username: "admin"
created_at: 0
```

> The rule's body is dynamic, it can be either `FIND`, `MATCH` or `FIND$` and `MATCH$`. The `$` symbol represents an exact match and could be replaced with another field like `exact: true|false`.

</details>

> [!Note]
> Usernames and names must be unique, so we could use them as IDs.

**Comment by QU3B1M** [comment]
Until now, the design considered one index per entity and related them by referencing their IDs. We understand that this is not ideal for a multi-tenant environment and that a single large index is better than multiple small ones.  

For this reason, we aim to have only two indexes: one containing the default resources (which will be used by all tenants) and the other containing all the tenant's custom information.  

Each document will include all the necessary information: _users_, _roles_, _policies_, and _rules_, these elements will be duplicated across documents if needed. 

All-in-one index example structure:
```yaml
# wazuh-users
- id: "id"
  name: "name"
  password: "password_hash"
  allow_run_as: false
  created_at: 0
  roles:
    - name: "admin"
      created_at: 0
      level: 0
      policies:
        - name: "policy-one"
          actions: ["agent:create"]
          resources: ["*:*:*"]
          effect: "allow"
          level: 0
          created_at: 0
        - name: "policy-two"
          actions: ["agent:remove"]
          resources: ["*:*:*"]
          effect: "allow"
          level: 0
          created_at: 0
      rules:
        - name: "rule-one"
          body: {}
          created_at: 0

```
