### ISSUE TITLE
CVE content index definition

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#325]
## Description

As we are centralizing the CVEs information in the indexer, we need to define the JSON schema of these documents using an index template. By defining the expected fields of an CVE document using an index template, we ensure the data is indexed under the expected format and no invalid / unexpected data gets through.

The goal of this issue is to analyze the JSON schema of a CVE document used by the CTI API, our data source, and define and generate an index template after these fields. The CTI snapshots provide a NDJSON file, containing a CVE document on each line. This document looks as follows:

<details><summary>Details</summary>
<p>

```json
{
  "name": "CVE-1999-0001",
  "offset": 1,
  "version": 1,
  "inserted_at": "2024-02-29T19:52:19.990862Z",
  "payload":
    {
      "containers":
        {
          "cna":
            {
              "affected":
                [
                  {
                    "cpes": ["cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*"],
                    "defaultStatus": "unaffected",
                    "product": "bsd_os",
                    "vendor": "bsdi",
                    "versions": [{ "status": "affected", "version": "3.1" }],
                  },
                  {
                    "cpes":
                      [
                        "cpe:2.3:o:freebsd:freebsd:1.0:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:1.1.5.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:1.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:1.2:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.0.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.0.5:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.0:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.1.5:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.1.6.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.1.6:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.1.7.1:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.1.7:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2.2:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2.3:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2.4:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2.5:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2.6:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2.8:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:2.2:*:*:*:*:*:*:*",
                        "cpe:2.3:o:freebsd:freebsd:3.0:*:*:*:*:*:*:*",
                      ],
                    "defaultStatus": "unaffected",
                    "product": "freebsd",
                    "vendor": "freebsd",
                    "versions":
                      [
                        { "status": "affected", "version": "1.0" },
                        { "status": "affected", "version": "1.1" },
                        { "status": "affected", "version": "1.1.5.1" },
                        { "status": "affected", "version": "1.2" },
                        { "status": "affected", "version": "2.0" },
                        { "status": "affected", "version": "2.0.1" },
                        { "status": "affected", "version": "2.0.5" },
                        { "status": "affected", "version": "2.1.5" },
                        { "status": "affected", "version": "2.1.6" },
                        { "status": "affected", "version": "2.1.6.1" },
                        { "status": "affected", "version": "2.1.7" },
                        { "status": "affected", "version": "2.1.7.1" },
                        { "status": "affected", "version": "2.2" },
                        { "status": "affected", "version": "2.2.2" },
                        { "status": "affected", "version": "2.2.3" },
                        { "status": "affected", "version": "2.2.4" },
                        { "status": "affected", "version": "2.2.5" },
                        { "status": "affected", "version": "2.2.6" },
                        { "status": "affected", "version": "2.2.8" },
                        { "status": "affected", "version": "3.0" },
                      ],
                  },
                  {
                    "cpes":
                      [
                        "cpe:2.3:o:openbsd:openbsd:2.3:*:*:*:*:*:*:*",
                        "cpe:2.3:o:openbsd:openbsd:2.4:*:*:*:*:*:*:*",
                      ],
                    "defaultStatus": "unaffected",
                    "product": "openbsd",
                    "vendor": "openbsd",
                    "versions":
                      [
                        { "status": "affected", "version": "2.3" },
                        { "status": "affected", "version": "2.4" },
                      ],
                  },
                ],
              "descriptions":
                [
                  {
                    "lang": "en",
                    "value": "ip_input.c in BSD-derived TCP/IP implementations allows remote attackers to cause a denial of service (crash or hang) via crafted packets.",
                  },
                  {
                    "lang": "es",
                    "value": "ip_input.c en implementaciones de TCP/IP derivadas de BSD permiten a atacantes remotos causar una denegación de servicio (cuelgue o caída) mediante paquetes artesanales.",
                  },
                ],
              "metrics":
                [
                  {
                    "cvssV2_0":
                      {
                        "accessComplexity": "LOW",
                        "accessVector": "NETWORK",
                        "authentication": "NONE",
                        "availabilityImpact": "PARTIAL",
                        "baseScore": 5,
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
                        "version": "2.0",
                      },
                    "format": "CVSS",
                  },
                ],
              "problemTypes":
                [
                  {
                    "descriptions":
                      [
                        {
                          "cweId": "CWE-20",
                          "description": "CWE-20",
                          "lang": "en",
                        },
                      ],
                  },
                ],
              "providerMetadata":
                {
                  "dateUpdated": "2010-12-16T05:00:00Z",
                  "orgId": "00000000-0000-4000-A000-000000000003",
                  "shortName": "nvd",
                  "x_subShortName": "nvd",
                },
              "references":
                [
                  { "url": "http://www.openbsd.org/errata23.html#tcpfix" },
                  { "url": "http://www.osvdb.org/5707" },
                ],
            },
        },
      "cveMetadata":
        {
          "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
          "assignerShortName": "mitre",
          "cveId": "CVE-1999-0001",
          "datePublished": "1999-12-30T05:00:00Z",
          "dateUpdated": "2010-12-16T05:00:00Z",
          "state": "PUBLISHED",
        },
      "dataType": "CVE_RECORD",
      "dataVersion": "5.0",
    },
}
``` 

</p>
</details> 

The index template must be defined and generated as per our tools in `wazuh-indexer-plugins/ecs`.

## Functional requirements

- The index template must provide mappings for any valid CVE document provided by CTI.
- The index template must reject documents with unexpected fields (strict mode).

## Implementation restrictions

- Use our tools in [ecs/](https://github.com/wazuh/wazuh-indexer-plugins/tree/main/ecs)

## Plan

- [x] Analyze the JSON schema of CVE documents.
- [x] Define and generate the index template.
- [x] Implement the event generator.
- [x] Add the index template to the setup plugin.
- [x] Add technical documentation.

**Comment by Dwordcito** [comment]
VD uses the CVE5 schema, probably this json schema could be the base for this development.

https://github.com/CVEProject/cve-schema/blob/main/schema/CVE_Record_Format.json

**Comment by QU3B1M** [comment]
Initial version of the CVE index ECS subset definition (WIP)

```yaml
---
name: wazuh-cve
fields:
  base:
    fields:
      tags: []
  cve:
    fields:
      name: {}
      offset: {}
      version: {}
      inserted_at: {}
      containers:
        fields:
          affected:
            fields:
              cpes: []
              default_status: {}
              product: {}
              vendor: {}
              versions:
                fields:
                  status: {}
                  version: {}
          descriptions:
            fields:
              lang: {}
              value: {}
          metrics:
            fields:
              format: {}
              cvss_v2:
                fields:
                  access_vector: {}
                  access_complexity: {}
                  authentication: {}
                  availability_impact: {}
                  base_score: {}
                  confidentiality_impact: {}
                  integrity_impact: {}
                  vector_string: {}
                  version: {}
            problem_types:
              fields:
                descriptions:
                  fields:
                    cwe_id: {}
                    description: {}
                    lang: {}
              provider_metadata:
                fields:
                  date_updated: {}
                  org_id: {}
                  short_name: {}
                  x_sub_short_name: {}
              references: []
      data_type: {}
      data_version: {}
      cve_metadata:
        fields:
          assigner_org_id: {}
          assigner_short_name: {}
          date_published: {}
          date_updated: {}
          state: {}

```
