### ISSUE TITLE
[BUG] `query.default_field` lists unused `host` object in `wazuh-agents` template

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer-plugins#329]
## Description

The `query.default_field` in the `wazuh-agents` template lists a `host` object outside `agent`.

* [index-template-agent.json](https://github.com/wazuh/wazuh-indexer-plugins/blob/f5ecffe5212750c62eeb97b8ded8f972cebd0884/plugins/setup/src/main/resources/index-template-agent.json#L259)

```shellsession
$ cat index-template-agent.json | jq '.settings.index."query.default_field"[]'
"agent.id"
"agent.name"
"agent.type"
"agent.version"
"agent.name"
"host.os.full"
"host.ip"
```

We need to move these into the `agent` object that since all `host` fields are included beneath `agent` now.

```yaml
---
name: agent
fields:
  base:
    fields:
      tags: []
  agent:
    fields:
      id: {}
      name: {}
      type: {}
      version: {}
      groups: {}
      key: {}
      last_login: {}
      status: {}
      host:
        fields: "*"
```
