### ISSUE TITLE
ECS documentation improvement II

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#346]
## Description

In https://github.com/wazuh/wazuh-indexer-plugins/issues/321, we improved the ECS documentation by migrating our hand-maintained Markdown documentation to CSV files generated automatically on changes to the schema.

We now will improve this documentation even more by filling up the missing information for the custom fields. For example, if we look at the [states-inventory-ports](https://github.com/wazuh/wazuh-indexer-plugins/blob/main/ecs/states-inventory-ports/docs/fields.csv), we can see that some of the custom fields do not have an example, or fields that are expected to be an array does not include such information.

![Image](https://github.com/user-attachments/assets/53e08ef3-397d-4942-9ee7-5e05f9957e54)

On this issue, we'll review every index definition, ensuring that:

- Custom fields that are expected to contain an array of values are properly normalized.
- Custom fields provide an example.
- Custom fields provide a description.
- The description is free of typos and ends with a period.

As an example:

```yml
    - name: rules
      type: keyword
      level: custom
      description: >
        Wazuh rules triggered by the event.
      normalize:
        - array
      example: "[\"foo\", \"bar\"]"
```
