### ISSUE TITLE
Implement commands index creation

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#42]
## Description

Include the latest version of the commands index template to the Command Manager plugin.

The fields of the command index are described on https://github.com/wazuh/wazuh-indexer/issues/349

Note: this index must be hidden.

**Comment by AlexRuiz7** [comment]
## `commands` index data model

### Fields summary

This index stores information about the commands executed by the agents. The index appears in 5.0.0 for the first time.

| ECS field                  | Type    | Description                                                                                                                         |
| -------------------------- | ------- | ----------------------------------------------------------------------------------------------------------------------------------- |
| \*`command.source`         | keyword | Origin of the request. One of [`Users/Services` (via Management API), `Engine` (via Management API), `Content manager` (directly)]. |
| \*`command.user`           | keyword | The user that originated the request. This user may represent a Management API or Indexer API user depending on the source.         |
| \*`command.target`         | keyword | Wazuh Server Cluster name to send the command to.                                                                                   |
| \*`command.type`           | keyword | The requested action type. One of [`agent_group`, `agent`, `wazuh_server`],                                                         |
| \*`command.action.type`    | keyword | The actual requested action. One of [Agent groups, Agent, Server cluster].                                                          |
| \*`command.action.args`    | keyword | Array of command arguments, starting with the absolute path to the executable.                                                      |
| \*`command.action.version` | keyword | Version of the command's schema.                                                                                                    |
| \*`command.timeout`        | short   | Time window in which the command has to be sent to its target.                                                                      |
| \*`command.status`         | keyword | Status within the Command Manager's context. One of [`pending`, `sent`, `success`, `failure`].                                      |
| \*`command.result.code`    | short   | Status code returned by the target.                                                                                                 |
| \*`command.result.message` | keyword | Result message returned by the target.                                                                                              |
| \*`command.result.data`    | keyword | Result data returned by the target.                                                                                                 |
| \*`command.request_id`     | short   | Unique identifier generated by the Command Manager. Auto-incremental.                                                               |
| \*`command.order_id`       | join    | Unique identifier generated by the Command Manager. Auto-incremental within the same Command Request ID.                            |
| \*`command.id`             | short   | Document ID. Generated combining the Order ID and the Command Request ID. This is the document ID, not part of the document.        |

\* Custom field.

### ECS mapping

```yml
---
- name: commands
  title: Commands
  description: >
    This index stores information about the Wazuh's commands. These commands can be sent to agents or Wazuh servers.
  fields:
    - name: source
      type: keyword
      description: >
        Origin of the request. One of `Users/Services` (via Management API), `Engine` (via Management API), `Content manager` (directly).
    - name: user
      type: keyword
      description: >
        The user that originated the request. This user may represent a Management API or Indexer API user depending on the source.
    - name: target
      type: keyword
      description: >
        Wazuh Server Cluster name to send the command to.
    - name: type
      type: keyword
      description: >
        The requested action type. One of `agent_group`, `agent`, `wazuh_server`.
    - name: action.type
      type: keyword
      description: >
        The actual requested action. One of Agent groups, Agent, Server cluster.
    - name: action.args
      type: keyword
      description: >
        Array of command arguments, starting with the absolute path to the executable.
    - name: action.version
      type: keyword
      description: >
        Version of the command's schema.
    - name: timeout
      type: short
      description: >
        Time window in which the command has to be sent to its target.
    - name: status
      type: keyword
      description: >
        Status within the Command Manager's context. One of `pending`, `sent`, `success`, `failure`.
    - name: result.code
      type: short
      description: >
        Status code returned by the target.
    - name: result.message
      type: keyword
      description: >
        Result message returned by the target.
    - name: result.data
      type: keyword
      description: >
        Result data returned by the target.
    - name: request_id
      type: short
      description: >
        Unique identifier generated by the Command Manager. Auto-incremental.
    - name: order_id
      type: join
      description: >
        Unique identifier generated by the Command Manager. Auto-incremental within the same Command Request ID.
```

### Index settings

```json
{
    "index_patterns": [".commands*"],
    "priority": 1,
    "template": {
        "settings": {
            "index": {
                "hidden": true,
                "number_of_shards": "1",
                "number_of_replicas": "0",
                "refresh_interval": "5s",
                "query.default_field": [
                  "command.source", 
                  "command.target", 
                  "command.status", 
                  "command.type",
                ]
            }
        }
    }
}
```
