### ISSUE TITLE
Create Wazuh Indexer users and roles

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-indexer-plugins#462]
## Description

Based on the research performed on https://github.com/wazuh/wazuh-indexer-plugins/issues/467, implement the required users and roles into the corresponding configuration files

| Index                                    | state model | User      | Permissions |
| ---------------------------------------- | ----------- | --------- | ----------- |
| `wazuh-states-*`                         | stateful    | Server    | read-write  |
| `wazuh-alerts*`, `wazuh-archives*`       | stateless   | Server    | write-only  |
| `wazuh-states-*`                         | stateful    | Dashboard | read-only   |
| `wazuh-alerts*`, `wazuh-archives*`       | stateless   | Dashboard | read-only   |
| `wazuh-monitoring*`, `wazuh-statistics*` | stateless   | Dashboard | read-write  |
| `*-sample-*`                             | stateless   | Dashboard | management  |

\*`management` equals to full permissions on these indices.

> [!NOTE]
> The roles and users are defined on the `yaml` files inside the directory `distribution/src/config/security/`

### Plan

- [x] Add Roles and Users `yaml` definitions
- [x] Generate corresponding documentation
- [ ] Meet up with @wazuh-devel-xdrsiem-dashboard, @wazuh-devel-devops and @wazuh/devel-xdrsiem-server to sync up about this development.

**Comment by QU3B1M** [comment]
## Documentation

Wazuh defined internal users and roles to manage the different indexes.

### Users

| User             | Description                                                                                     | Backend Roles                                                                                                                       |
| ---------------- | ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------- |
| `wazuhserver`    | Server-side user with read/write access to stateful and write-only access to stateless.         | `server-stateful-read-write`, `server-stateless-write-only`                                                                         |
| `wazuhdashboard` | Dashboard user with read access to stateful/stateless, and write access to monitoring indices.  | `dashboard-stateful-read-only`, `dashboard-stateless-read-only`, `dashboard-stateless-read-write`, `dashboard-stateless-management` |

---

### Roles

| Role Name                        | Access Description                                                   | Index Patterns                           | Permissions                         |
| -------------------------------- | -------------------------------------------------------------------- | ---------------------------------------- | ----------------------------------- |
| `server-stateful-read-write`     | Read and write access to stateful index data                         | `wazuh-states-*`                         | `read`, `index`                     |
| `server-stateless-write-only`    | Write-only access to stateless alert and archive indexes             | `wazuh-alerts*`, `wazuh-archives*`       | `index`                             |
| `dashboard-stateful-read-only`   | Read-only access to stateful indexes from Dashboards                 | `wazuh-states-*`                         | `read`                              |
| `dashboard-stateless-read-only`  | Read-only access to stateless alert and archive indexes              | `wazuh-alerts*`, `wazuh-archives*`       | `read`                              |
| `dashboard-stateless-read-write` | Read/write access to monitoring and statistics indexes               | `wazuh-monitoring*`, `wazuh-statistics*` | `read`, `index`                     |
| `dashboard-stateless-management` | Full access (read, delete, manage, index) to internal dashboard data | `*-sample-*`                             | `read`, `delete`, `manage`, `index` |

---

## Configuration Files

### `roles.wazuh.yml`

Defines each role’s permissions on relevant index patterns.

<details><summary>full yaml file</summary>

```yaml
server-stateful-read-write:
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-states-*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
    - "index"
  tenant_permissions: []
  static: true

server-stateless-write-only:
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-alerts*"
    - "wazuh-archives*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "index"
  tenant_permissions: []
  static: true

dashboard-stateful-read-only:
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-states-*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
  tenant_permissions: []
  static: true

dashboard-stateless-read-only:
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-alerts*"
    - "wazuh-archives*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
  tenant_permissions: []
  static: true

dashboard-stateless-read-write:
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-monitoring*"
    - "wazuh-statistics*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
    - "index"
  tenant_permissions: []
  static: true

dashboard-stateless-management:
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "*-sample-*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
    - "delete"
    - "manage"
    - "index"
  tenant_permissions: []
  static: true

```
</details>

---

### `internal_users.wazuh.yml`

Declared users with its hashed passwords (bcrypt), with assigned backend roles.

<details><summary>full yaml file</summary>

```yaml
wazuhserver:
  # The hash is the hash of the password "wazuhserver"
  hash: "$2b$12$F2AcDHixU0NJelALgC4LU.7Ac5OsxgXPh5kALHiuBu2ftstDBHoQ."
  reserved: false
  backend_roles:
  - "server-stateful-read-write"
  - "server-stateless-write-only"
  description: "Server user with read/write access to stateful and write-only access to stateless indexes"
wazuhdashboard:
  # The hash is the hash of the password "wazuhdashboard"
  hash: "$2b$12$HYNejpgq0WUQ3a4hFvbGOOtvgE0H/pH7OqMhlHHRM0Ziu4V3EF/8y"
  reserved: false
  backend_roles:
  - "dashboard-stateful-read-only"
  - "dashboard-stateless-read-only"
  - "dashboard-stateless-read-write"
  - "dashboard-stateless-management"
  description: "Dashboard user with read access to stateful and stateless indexes, and write access to stateless management indexes"
```
</details>

---

### `roles_mapping.wazuh.yml`

Maps backend roles to their corresponding roles.

<details><summary>full yaml file</summary>

```yaml
server-stateful-read-write:
  reserved: false
  hidden: false
  backend_roles:
    - "server-stateful-read-write"
  users: []
  hosts: []
  and_backend_roles: []

server-stateless-write-only:
  reserved: false
  hidden: false
  backend_roles:
    - "server-stateless-write-only"
  users: []
  hosts: []
  and_backend_roles: []

dashboard-stateful-read-only:
  reserved: false
  hidden: false
  backend_roles:
    - "dashboard-stateful-read-only"
  users: []
  hosts: []
  and_backend_roles: []

dashboard-stateless-read-only:
  reserved: false
  hidden: false
  backend_roles:
    - "dashboard-stateless-read-only"
  users: []
  hosts: []
  and_backend_roles: []

dashboard-stateless-read-write:
  reserved: false
  hidden: false
  backend_roles:
    - "dashboard-stateless-read-write"
  users: []
  hosts: []
  and_backend_roles: []

dashboard-stateless-management:
  reserved: false
  hidden: false
  backend_roles:
    - "dashboard-stateless-management"
  users: []
  hosts: []
  and_backend_roles: []
```
</details>
